version: '3.8'

services:
  nginx:
    container_name: app
    image: nginx:latest
    ports:
      - "82:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=usercar.loc
  php74:
    container_name: php74
    build: docker/php74
    ports:
      - 9002:9000
    volumes:
      - .:/var/www/html/
  mysql:
    container_name: mysql8
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/my.cnf